### PR TITLE
fix[protocol-sd]: add register center params check

### LINKED ISSUE #4046: [BUG] <title> nacos 服务发现
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Image

使用nacos 服务发现进行添加监控，服务发现 Host 和  Port ，填写假数据甚至于胡乱填写，点击最下方测试 显示“测试连接成功”

### Expected Behavior

正确显示测试结果

### Steps To Reproduce

_No response_

### Environment

```markdown
HertzBeat version(s): v1.8.0
```

### Debug logs

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by yuluo-yx**
- Fixed #4046

### CODE REVIEW

File: hertzbeat-common-core/src/main/java/org/apache/hertzbeat/common/entity/job/protocol/DnsSdProtocol.java [hunk 1]
```diff
@@ -30,12 +30,19 @@
...
     private String port;
 
     private String recordType;
 
     private String recordName;
+
+    @Override
+    public boolean isInvalid() {
+
+        // todo: add
```
Comment (yuluo-yx) [inline hertzbeat-common-core/src/main/java/org/apache/hertzbeat/common/entity/job/protocol/DnsSdProtocol.java:45]: i think we can improve on this later; there's so much more to it.
