### PR TITLE
[bugfix] webhook template json escape

### LINKED ISSUE #2524: [BUG] <title>webhook send alter message error
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

During alarm recovery, sending a message containing a threshold expression causes the content field to contain special characters
for example：
{
  "alarmId": 76456,
  "target": "${target}",
  "thresholdId": 33455,
  "priority": 0,
  "content": "alert **** , status("up")",
  "status": 0,
  "times": 1,
  "triggerTime": "2022-02-25T13:32:13",
  "tags": {
    "app": "windows",
    "monitorId": "180427708350720",
    "metrics": "availability",
    "code": "UN_CONNECTABLE",
    "thresholdId": "112",
    "monitorName": "WINDOWS_192.168.124.12"
  }
}

"content"  is not a valid JSON format and has not been escaped

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```markdown
HertzBeat version(s): 1.6.0
```

### Debug logs

no logs

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pwallk**
## What's changed?
fixed #2524

image
image

## Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
- [x]  I have written the necessary doc or comment.
- [x]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [ ] I have added the necessary [e2e tests](https://github.com/apache/hertzbeat/tree/master/e2e) and all cases have passed.

### CODE REVIEW

File: manager/src/main/java/org/apache/hertzbeat/manager/component/alerter/impl/AbstractAlertNotifyHandlerImpl.java [hunk 1]
```diff
@@ -115,6 +115,42 @@ protected String renderContent(NoticeTemplate noticeTemplate, Alert alert) throw
...
+
+        StringBuilder sb = new StringBuilder();
+        for (char c : jsonStr.toCharArray()) {
+            switch (c) {
+                case '"':
+                    sb.append("\\\"");
+                    break;
+                case '\\':
+                    sb.append("\\\\");
+                    break;
```
Comment (tomsun28) [inline manager/src/main/java/org/apache/hertzbeat/manager/component/alerter/impl/AbstractAlertNotifyHandlerImpl.java:131]: Hi, should we consider the char `/` here?

**Review by tomsun28 — APPROVED** [review]
lgtm!
