### PR TITLE
[bugfix] fix service discovery host field  NullPointerException

### LINKED ISSUE #3764: [BUG] <title>return value of "org.apache.hertzbeat.common.entity.manager.Monitor.getHost()" is null
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

1.7.3 添加 auto监控 Prometheus 的http sd  提交后报错， 

新增监控失败
Cannot invoke "String.trim()" because the return value of "org.apache.hertzbeat.common.entity.manager.Monitor.getHost()" is null

Image

一下是 1.7.2 保存后的： 

Image

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```markdown
HertzBeat version(v1.7.3):
```

### Debug logs

2025-09-11 16:22:28.202 [http-nio-1157-exec-1] ERROR org.apache.hertzbeat.manager.support.GlobalExceptionHandler Line:252 - [monitor]-[unknown error happen]-Cannot invoke "String.trim()" because the return value of "org.apache.hertzbeat.common.entity.manager.Monitor.getHost()" is null
java.lang.NullPointerException: Cannot invoke "String.trim()" because the return value of "org.apache.hertzbeat.common.entity.manager.Monitor.getHost()" is null
        at org.apache.hertzbeat.manager.service.impl.MonitorServiceImpl.validate(MonitorServiceImpl.java:273)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:359)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:380)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:727)
        at org.apache.hertzbeat.manager.service.impl.MonitorServiceImpl$$SpringCGLIB$$0.validate(<generated>)
        at org.apache.hertzbeat.manager.controller.MonitorController.addNewMonitor(MonitorController.java:58)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:257)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:190)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pwallk**
## What's changed?

fix #3764

## Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
- [x]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [ ] I have added the necessary [e2e tests](https://github.com/apache/hertzbeat/tree/master/e2e) and all cases have passed.

### CODE REVIEW

**Comment by Duansg** [comment]
Oh, right, one more thing—if it's service discovery monitoring, the `Monitor Real-Time Detail` should display the service discovery address and port. Even if the `host` validation is skipped, the information shown here is still problematic.

**Comment by pwallk** [comment]
> Oh, right, one more thing—if it's service discovery monitoring, the should display the service discovery address and port. Even if the validation is skipped, the information shown here is still problematic.`Monitor Real-Time Detail``host`

This PR only addresses the issue of `Service Discovery` not functioning properly. Only skipping the verification of the `host` field for `Monitor` instead of `Service Discovery`. Currently, `Service Discovery` does not have a unified `host` and `port` field, for example, `http_sd` only has one `URL` field. Perhaps in the future, unification can be achieved

**Comment by Duansg** [comment]
> This PR only addresses the issue of Service Discovery not functioning properly. Only skipping the verification of the host field for Monitor instead of Service Discovery. Currently, Service Discovery does not have a unified host and port field, for example, http_sd only has one URL field. Perhaps in the future, unification can be achieved

Understood, then I will carry out the follow-up optimization. 😄

File: hertzbeat-collector/hertzbeat-collector-collector/src/main/java/org/apache/hertzbeat/collector/metrics/HertzBeatMetricsCollector.java [hunk 1]
```diff
@@ -58,6 +58,10 @@ public void recordCollectMetrics(Job job, long durationMillis, String status) {
         Map<String, String> metadata = job.getMetadata();
         String monitorName = metadata != null ? metadata.get("instancename") : "unknown";
         String monitorTarget = metadata != null ? metadata.get("instancehost") : "unknown";
+        // todo can not get the host from service discovery
+        if (monitorTarget == null) {
```
Comment (Aias00) [inline hertzbeat-collector/hertzbeat-collector-collector/src/main/java/org/apache/hertzbeat/collector/metrics/HertzBeatMetricsCollector.java]: StringUtils.isBlank

File: hertzbeat-manager/src/main/java/org/apache/hertzbeat/manager/service/impl/MonitorServiceImpl.java [hunk 2]
```diff
@@ -276,7 +276,8 @@ public void importConfig(MultipartFile file) throws Exception {
     public void validate(MonitorDto monitorDto, Boolean isModify) throws IllegalArgumentException {
         // The request monitoring parameter matches the monitoring parameter definition mapping check
         Monitor monitor = monitorDto.getMonitor();
-        monitor.setHost(monitor.getHost().trim());
+        // The Service Discovery host field may be null
+        monitor.setHost(monitor.getHost() != null ? monitor.getHost().trim() : "");
```
Comment (Aias00) [inline hertzbeat-manager/src/main/java/org/apache/hertzbeat/manager/service/impl/MonitorServiceImpl.java]: StringUtils.isBlank
